POST http://localhost:3000/addUser
Content-type: application/json

{
  "name": "naturo",
  "age": 30
}

###
GET http://localhost:3000/

###
PUT http://localhost:3000/updateUser/<id>
Content-type: application/json

{
  "name": "sasuke",
  "age": 30
}

###
DELETE  http://localhost:3000/deleteUser/<id>
Content-type: application/json
